theme: jekyll-theme-minimal
title: Julie's Website
description: This is a test to see where this text goes.

exclude [README.md]


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "DSC_0770.JPG"
